"""Generate `ERRORS.md` from `inferrail.errors.codes` — the single source
of truth for every stable Inferrail error code.

Run directly to regenerate:

    python scripts/generate_errors_md.py

CI runs this, then `git diff --exit-code ERRORS.md` — edit
`src/inferrail/errors/codes.py`, never this file directly.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from inferrail.errors.codes import all_codes, docs_url_for  # noqa: E402

_OUTPUT_PATH = Path(__file__).resolve().parent.parent / "ERRORS.md"

_HEADER = """\
# Inferrail — Error Codes

Generated from `src/inferrail/errors/codes.py` by
`scripts/generate_errors_md.py` — do not edit this file directly.

Every error the gateway returns carries one of these codes in its JSON
body's `error.code` field, alongside `error.remediation` (what to do
about it) and `error.docs_url` (this file, anchored to the code):

```json
{
  "error": {
    "message": "...",
    "type": "RoutingError",
    "code": "INFERRAIL_E007",
    "remediation": "Use one of the route names under inferrail.yaml's routes: section.",
    "docs_url": "https://github.com/domondi1/inferrail/blob/main/ERRORS.md#inferrail_e007"
  }
}
```

| Code | Exception type | Meaning | Remediation |
|---|---|---|---|
"""


def generate() -> str:
    rows = []
    for exc_type, code in all_codes():
        anchor = code.code.lower()
        rows.append(
            f'| <a id="{anchor}"></a>`{code.code}` | `{exc_type.__name__}` | '
            f"{code.summary} | {code.remediation} |"
        )
    return _HEADER + "\n".join(rows) + "\n"


def main() -> None:
    text = generate()
    _OUTPUT_PATH.write_text(text, encoding="utf-8")
    print(f"Wrote {_OUTPUT_PATH}")
    # Prove docs_url_for actually resolves to a real anchor in what we just
    # wrote, so the generator can't silently drift from the URL scheme
    # gateway/app.py hands back to callers.
    for _, code in all_codes():
        assert f'id="{code.code.lower()}"' in text, code.code
    assert docs_url_for("INFERRAIL_E001").endswith("#inferrail_e001")


if __name__ == "__main__":
    main()
